$(document).ready(function() {
  console.log("Script included!");
  $('#ingredient1').click(function(){
  	$('#ingredient1').addClass('highlighted');
  });
  $('#ingredient2').click(function(){
  	$('#ingredient2').addClass('highlighted');
  });
  $('#ingredient3').click(function(){
  	$('#ingredient3').addClass('highlighted');
  });
  $('#ingredient4').click(function(){
  	$('#ingredient4').addClass('highlighted');
  });
  $('#ingredient5').click(function(){
  	$('#ingredient5').addClass('highlighted');
  });
  $('#ingredient6').click(function(){
  	$('#ingredient6').addClass('highlighted');
  });
  $('#ingredient7').click(function(){
  	$('#ingredient7').addClass('highlighted');
  });
  $('#ingredient8').click(function(){
  	$('#ingredient8').addClass('highlighted');
  });
  $('#ingredient9').click(function(){
  	$('#ingredient9').addClass('highlighted');
  });
  $('#ingredient10').click(function(){
  	$('#ingredient10').addClass('highlighted');
  });
  $('#ingredient11').click(function(){
  	$('#ingredient11').addClass('highlighted');
  });
  $('#ingredient12').click(function(){
  	$('#ingredient12').addClass('highlighted');
  });
  $('#ingredient13').click(function(){
  	$('#ingredient13').addClass('highlighted');
  });
  $('#ingredient14').click(function(){
  	$('#ingredient14').addClass('highlighted');
  });
   $('#button').click(function(){
   	$("img").hide();
   });
   $('#direction1').click(function(){
  	$('#direction1').toggleClass('underline');
  });
    $('#direction2').click(function(){
  	$('#direction2').toggleClass('underline');
  });
     $('#direction3').click(function(){
  	$('#direction3').toggleClass('underline');
  });
      $('#direction4').click(function(){
  	$('#direction4').toggleClass('underline');
  });
});
